name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main   # or your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        echo "${{ secrets.SECRET3 }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy Docker container on EC2
      env:
        HOST: ${{ secrets.SECRET1 }}
        USER: ${{ secrets.EC2_SECRET2 }}
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $USER@$HOST << 'EOF'
          docker pull akshayvyas12/my-html-site:latest
          docker stop my-html-site || true
          docker rm my-html-site || true
          docker run -d --name my-html-site -p 80:80 akshayvyas12/my-html-site:latest
        EOF
