name: Deploy HTML Site to EC2

# Trigger this workflow on every push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Expose EC2_HOST and EC2_USER as environment variables in this job
    env:
      HOST: ${{ secrets.SECRET1 }}
      USER: ${{ secrets.SECRET2 }}

    steps:
      # 1) Always checkout the repo (not strictly needed for a pure-SSH deploy, but good practice)
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Write the SSH private key to ~/.ssh/id_rsa and set correct permissions
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SECRET3 }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Add the EC2 host to known_hosts to avoid interactive prompt
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

      # 3) SSH into EC2 and pull + run your Docker image
      - name: Deploy Docker container on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $USER@$HOST << 'EOF'
            docker pull akshayvyas12/my-html-site
            docker stop my-html-site || true
            docker rm my-html-site || true
            docker run -d --name my-html-site -p 80:80 akshayvyas12/my-html-site
          EOF
