name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Save EC2 Key
        run: |
          echo "${{ secrets.front-app.pem }}" > front-app.pem
          chmod 600 front-app.pem

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.ubuntu }}@${{ secrets.3.137.208.106 }} << 'EOF'
            docker pull akshayvyas12/my-html-site
            docker stop frontend || true
            docker rm frontend || true
            docker run -d -p 80:80 --name frontend akshayvyas12/my-html-site
          EOF
