name: Deploy HTML Site to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      HOST: ${{ secrets.SECRET1 }}     # e.g. 3.137.208.106
      USER: ${{ secrets.SECRET2 }}     # e.g. ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SECRET3 }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

      - name: Deploy Docker Image
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $USER@$HOST << 'EOF'
            docker pull akshayvyas12/my-html-site:latest
            docker stop my-html-site || true
            docker rm my-html-site || true
            docker run -d --name my-html-site -p 80:80 akshayvyas12/my-html-site:latest
          EOF
